sudo: required
language: node_js
node_js:
  - "0.10.31"
before_install:
  - "chmod +x travis.sh"
install:
  - "curl https://install.meteor.com | /bin/sh"
services:
  - mongodb
script:
  - "./travis.sh"